### ISSUE TITLE
Activate / Desactivate Action

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#38]
Add to all configuration "Activate" "Desactivate" action.
In the configurations list, click direcly on status to change beetween activate / desactivate
In the configuration View, click on the status element to change beetween activate / desactivate
In each case, display the success of the operation in a snack notify status

**Comment by Eronne** [comment]
# TODOs

## General
- [ ]  Refacto `src/components/common/chips/ActivatedStatusChip`

## ConfigurationsListing
- [ ] `storage-to-table`
- [ ] `tables-to-tables`

## ConfigurationView
- [ ] `storage-to-storage`
- [ ] `storage-to-table`
- [ ] `gcs-to-gcs`
- [ ] `tables-to-tables`
- [ ] `gbq-to-gcs`
- [ ] `table-to-storage`
